Feature complete auto complete path
AY2425S1-CS2103T-W10-4/tp pull request #106
Opened 2024-10-27 08:55 UTC by Jianwen0451

2024-10-27 15:31 UTC, isaactodo requested changes
Some nesting issues. Also, I think that the stuff you added feels more suitable as a static method inside something like StorageManager, then the autocompleteparser can just call the static method to get a list of valid files.

2024-10-27 15:31 UTC, isaactodo commented on src/main/java/seedu/address/logic/parser/AutocompleteParser.java
> +    }
Can use guard clauses to reduce nesting

2024-10-28 02:19 UTC, Jianwen0451 commented on src/main/java/seedu/address/logic/parser/AutocompleteParser.java
> +    }
Resolve the nesting issue. These methods should not be in Storage manager or Storage as it will create unnecessary coupling. These methods scan the directory and get the file name rather than reading or editing the file (which storage does). So I think these methods should remain in autocomplete parser.

2024-10-28 04:02 UTC, tanyqcollin commented on src/main/java/seedu/address/logic/parser/AutocompleteParser.java
> +     * checks if the given file is a json file.
The first word should be upper case.

2024-10-28 04:12 UTC, Jianwen0451 commented on src/main/java/seedu/address/logic/parser/AutocompleteParser.java
> +     * checks if the given file is a json file.
Changed

2024-10-28 04:51 UTC, isaactodo approved these changes
LGTM!

2024-10-28 04:58 UTC, tanyqcollin approved these changes
LGTM!

2024-10-28 07:10 UTC, merged