Update ug webpage
AY2425S1-CS2103T-W10-4/tp pull request #146
Opened 2024-11-04 09:46 UTC by Jianwen0451

1. Update the main page with a left margin to prevent the main page and sidebar collapse together
2. Use the dynamic side of the sidebar rather than fix it to prevent overlapping when the screen it too large or too small
3. See the current version at [here] (https://jianwen0451.github.io/tp/UserGuide.html)

2024-11-04 12:11 UTC, isaactodo requested changes
LGTM!

2024-11-04 12:11 UTC, isaactodo commented on docs/_config.yml
> +repository: "Jianwen0451/tp"
I think you forgot to change this back, not sure if it will affect the pages deployment though

2024-11-05 04:08 UTC, Jianwen0451 commented on docs/_config.yml
> +repository: "Jianwen0451/tp"
Change back

2024-11-05 12:59 UTC, isaactodo approved these changes
LGTM!

2024-11-06 02:11 UTC, merged