Fix Bug for Filter and Edit
AY2425S1-CS2103T-W10-4/tp pull request #252
Opened 2024-11-09 03:19 UTC by tanyqcollin

- Fix the issue that `Module` parameter accepting empty input and did not throw exception that cause by `Collections.emptyList()`

2024-11-09 07:31 UTC, Jianwen0451 requested changes
The issue #242 is a feature flaw (Error message not clear), rather than a functionality bug. Please undo the change of the error message

2024-11-09 07:31 UTC, Jianwen0451 commented on src/main/java/seedu/address/logic/commands/FilterCommand.java
> +            + "Example: " + COMMAND_WORD + " n/Alex m/Chemistry";
I think this part is not a bug fix. It is a feature tweak as it is trying to make the error message of FilterCommand more specific. Please Undo this part

2024-11-09 07:39 UTC, Jianwen0451 commented
Also Fixing #208 also seems not appropriate. 

<img width="886" alt="Screenshot 2024-11-09 at 3 35 38 PM" src="https://github.com/user-attachments/assets/0d36d334-cd97-4e9a-9611-9722656069ad">

As stated here, the garbage-in garbage-out is not necessarily "incorrect" and can be considered as a feature update.

My suggestion is to undo the change and just say in UG that enter empty tags will match for all students

2024-11-09 08:01 UTC, tanyqcollin commented
> Also Fixing #208 also seems not appropriate.
> 
> <img alt="Screenshot 2024-11-09 at 3 35 38 PM" width="886" src="https://private-user-images.githubusercontent.com/147498698/384586684-0d36d334-cd97-4e9a-9611-9722656069ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzg2OTYsIm5iZiI6MTczMTEzODM5NiwicGF0aCI6Ii8xNDc0OTg2OTgvMzg0NTg2Njg0LTBkMzZkMzM0LWNkOTctNGU5YS05NjExLTk3MjI2NTYwNjlhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2RiYzg5YzkzZDI2OGY0YjU3ZDMwMzU4NTBlZjI0MmQ1MDQ2YTlmMjkyZWRiZWE5YjM0YTczOTAwZjg4MDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nVR8w_wHBjmuQH_VQulHL2i_P6uQIiXSEiG9_bJDDRA">
> As stated here, the garbage-in garbage-out is not necessarily "incorrect" and can be considered as a feature update.
> 
> My suggestion is to undo the change and just say in UG that enter empty tags will match for all students

![image](https://github.com/user-attachments/assets/2ff6b92f-8e9b-4596-9996-7532350eee4f)
Previously, I noticed this issue with filtering empty tags, which I fixed on my local host in this commit https://github.com/AY2425S1-CS2103T-W10-4/tp/pull/154/commits/8959fddaf05800edc31e32e14145666b5703c561. However, after merging the branch, I did not test it again by filter with an empty tags, so I believe this might still considered as a bug.

2024-11-09 08:01 UTC, tanyqcollin commented on src/main/java/seedu/address/logic/commands/FilterCommand.java
> +            + "Example: " + COMMAND_WORD + " n/Alex m/Chemistry";
noted.

2024-11-09 08:29 UTC, Jianwen0451 commented
> > Also Fixing #208 also seems not appropriate.
> > <img alt="Screenshot 2024-11-09 at 3 35 38 PM" width="886" src="https://private-user-images.githubusercontent.com/147498698/384586684-0d36d334-cd97-4e9a-9611-9722656069ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzg2OTYsIm5iZiI6MTczMTEzODM5NiwicGF0aCI6Ii8xNDc0OTg2OTgvMzg0NTg2Njg0LTBkMzZkMzM0LWNkOTctNGU5YS05NjExLTk3MjI2NTYwNjlhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzQ2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lY2RiYzg5YzkzZDI2OGY0YjU3ZDMwMzU4NTBlZjI0MmQ1MDQ2YTlmMjkyZWRiZWE5YjM0YTczOTAwZjg4MDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nVR8w_wHBjmuQH_VQulHL2i_P6uQIiXSEiG9_bJDDRA">
> > As stated here, the garbage-in garbage-out is not necessarily "incorrect" and can be considered as a feature update.
> > My suggestion is to undo the change and just say in UG that enter empty tags will match for all students
> 
> ![image](https://private-user-images.githubusercontent.com/149695327/384587442-2ff6b92f-8e9b-4596-9996-7532350eee4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNDA3NDcsIm5iZiI6MTczMTE0MDQ0NywicGF0aCI6Ii8xNDk2OTUzMjcvMzg0NTg3NDQyLTJmZjZiOTJmLThlOWItNDU5Ni05OTk2LTc1MzIzNTBlZWU0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwODIwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDZmODBhYjdhZDIyMDUzZDQwNTQyMDJkZTg1NmM4OWQwYmQwM2ViNmM2NDM5ZDdkNDk0MTRhN2UxMjE2Zjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3DvCZW3wK-XBJOvh4idNpK9HcmYdUaVoQj1GdyVoybY) Previously, I noticed this issue with filtering empty tags, which I fixed on my local host in this commit [8959fdd](https://github.com/AY2425S1-CS2103T-W10-4/tp/commit/8959fddaf05800edc31e32e14145666b5703c561). However, after merging the branch, I did not test it again by filter with an empty tags, so I believe this might still considered as a bug.

In commit https://github.com/AY2425S1-CS2103T-W10-4/tp/commit/8959fddaf05800edc31e32e14145666b5703c561, I see you implement an orElse(true) at the end. This means that the predicate for the filter tag will be true if the give tag list is empty. This means that all persons will be listed when nothing but an empty tag list is given as input. So it is even not a wrong "output". This just means that it ***will be better*** if we disallow this and produce an error message. I am strongly against this change.  I suggest that we just play safe here, not changing it but can mention it in the DG "Planned Enhancement". The cost of making a feature change is too high for all of us.

2024-11-09 08:50 UTC, Jianwen0451 approved these changes

2024-11-10 07:09 UTC, yongqqqq approved these changes
LGTM!

2024-11-10 07:16 UTC, merged